apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-demo-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.build-acceptance-test: ""
    notifications.argoproj.io/subscribe.sync-operation-change.slack: 1-team-sqa
spec:
  project: default
  source:
    repoURL: 'https://github.com/huinno-yoseph/demo.git'
    targetRevision: HEAD
    path: 'k8s'  # Kubernetes manifests가 있는 디렉터리
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
