apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo
  labels:
    app: spring-boot-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-demo
  template:
    metadata:
      labels:
        app: spring-boot-demo
    spec:
      containers:
        - name: spring-boot-demo
          image: clmfkilu/spring-boot-demo:latest
          ports:
            - containerPort: 7001
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"